// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1RjNyhCvEcaQW6oj195D3oUA2Pk1zZ7g',
    appId: '1:551880581965:android:82180d1593daf5d7080d04',
    messagingSenderId: '551880581965',
    projectId: 'multigeot-419617',
    databaseURL: 'https://multigeot-419617-default-rtdb.firebaseio.com',
    storageBucket: 'multigeot-419617.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRKOc97ziL3Xyp21CQwUJaq8ShJ-vLpFU',
    appId: '1:551880581965:ios:41a364128083274e080d04',
    messagingSenderId: '551880581965',
    projectId: 'multigeot-419617',
    databaseURL: 'https://multigeot-419617-default-rtdb.firebaseio.com',
    storageBucket: 'multigeot-419617.appspot.com',
    iosBundleId: 'com.example.multigeo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGvHXn07hlsrWzoRXHHOQ2Rd_5AZlN7vc',
    appId: '1:551880581965:web:7c52ad309a6c469e080d04',
    messagingSenderId: '551880581965',
    projectId: 'multigeot-419617',
    authDomain: 'multigeot-419617.firebaseapp.com',
    databaseURL: 'https://multigeot-419617-default-rtdb.firebaseio.com',
    storageBucket: 'multigeot-419617.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGvHXn07hlsrWzoRXHHOQ2Rd_5AZlN7vc',
    appId: '1:551880581965:web:fcd6c688bae27121080d04',
    messagingSenderId: '551880581965',
    projectId: 'multigeot-419617',
    authDomain: 'multigeot-419617.firebaseapp.com',
    databaseURL: 'https://multigeot-419617-default-rtdb.firebaseio.com',
    storageBucket: 'multigeot-419617.appspot.com',
  );

}